### ISSUE TITLE
Can you please provide me with a full example of reading tags ?

### ISSUE THREAD

**Issue by Khairala** [revtel/react-native-nfc-manager#415]
sorry for asking but am still new in react native but reading NFC is required in the project am working on i've tried alot to read tags and read most of issues and searched YouTube but couldn't find any working example .
so can anyone plz provide me with reading example .

**Comment by SemihOzdogan** [comment]
@Khairala 
Yes, I agree with you that the documents are not enough and the usages are not clear. Can you please share a working example for reading and writing ? @whitedogg13

**Comment by godlatro** [comment]
better explain is using react-native-nfc-rewriter app
Just run this app and you see how it work

**Comment by SemihOzdogan** [comment]
@godlatro  thank you for information. I looked at that application but it couldn't help with some details.For example What is the NdefFormatable ? NdefFormatable convert to Ndef ?

**Comment by Pinwheeler** [comment]
+1 on this- the example usage is.... well, kinda bad- it's cut from the example app, and doesn't really work on its own.

Sending people to the example app isn't really ideal either because the example app has a huge amount of (undocumented) behavior and legacy dependencies [reconnect.js](https://www.npmjs.com/package/reconnect)

this repository needs a "simplest possible example" application and/or simplest possible usage. I'm going to try to figure out what that is and make a PR.
