### ISSUE TITLE
Ios default Read Nfc popup is opening with double click by cancel 

### ISSUE THREAD

**Issue by Krish143git** [revtel/react-native-nfc-manager#506]
@whitedogg13  Hi When I click Read nfc tag button Ios pop is opening. Instead of scanning the tag i cancel the popup.Now the popup is opening with double click . I am using your  example reference code this is the link (https://github.com/revtel/react-native-nfc-rewriter). i am facing the same issue in my application as well.Here i am attaching your application video of the isse for the reference. please help me how to avoid?

Package versions 
"react": "17.0.2",
"react-native": "0.66.0",
"react-native-nfc-manager": "^3.13.2",

https://user-images.githubusercontent.com/80909154/161269922-c2f8da56-83c8-4d91-b675-182db5065c7d.mp4

.

**Comment by Krish143git** [comment]
@rpaasche  Is there any chance to open a popup for next read action once cancel

**Comment by rpaasche** [comment]
> @rpaasche Is there any chance to open a popup for next read action once cancel

```
 if (ex instanceof NfcError.UserCancel) {
                Alert.alert('NFC Session UserCancel');
            } 
```

**Comment by rpaasche** [comment]
@whitedogg13 
I dived a bit deeper into it.

The problem is, that `cancelTechnologyRequest`, `invalidateSessionWithErrorIOS` and `invalidateSessionIOS` do not dealloc `session` and `tagSession` which causes `requestTechnology` to throw the error. 

According o the [docs](https://developer.apple.com/documentation/corenfc/nfcreadersession?language=objc) the code for requestTechnology should look like this:

```objc
RCT_EXPORT_METHOD(requestTechnology: (NSArray *)techs options: (NSDictionary *)options callback:(nonnull RCTResponseSenderBlock)callback)
{
    if (@available(iOS 13.0, *)) {
        if (tagSession == nil && session == nil) {
            tagSession = [[NFCTagReaderSession alloc]
                         initWithPollingOption:(NFCPollingISO14443 | NFCPollingISO15693) delegate:self queue:dispatch_get_main_queue()];
            tagSession.alertMessage = [options objectForKey:@"alertMessage"];
            [tagSession beginSession];
            techRequestTypes = techs;
            techRequestCallback = callback;
        } else if (tagSession != nil && ![tagSession ready]) {
            [tagSession beginSession];
            techRequestTypes = techs;
            techRequestCallback = callback;
        } else {
            callback(@[@"Duplicated registration", [NSNull null]]);
        }
    } else {
        callback(@[@"Not support in this device", [NSNull null]]);
    }
}
```
Disclaimer: I'm not familiar with objc, especially unsure about `![tagSession ready]`.

**Comment by Krish143git** [comment]
@whitedogg13 @rpaasche  please help how to proceed 
1) @rpaasche  if not possible to open the pop up second time when user cancel the popup where can i keep this code
   if (ex instanceof NfcError.UserCancel) {
                Alert.alert('NFC Session UserCancel');
            } 
 2) @whitedogg13 @rpaasche  if it is possible to open How to proceed?

**Comment by Krish143git** [comment]
@whitedogg13 @rpaasche  please share comments it is possible or not as per above comment.

**Comment by whitedogg13** [comment]
@Krish143git sorry for the late response! I will take a look into this one~

**Comment by rpaasche** [comment]
At the moment I'm using this pretty ugly workaround:
```typescript
import RNRestart from 'react-native-restart';
...
 if (ex instanceof NfcError.UserCancel) {
                // ignore user abortion
                if (Platform.OS === 'ios') {
                    RNRestart.Restart();
                }
            }
...
```

**Comment by whitedogg13** [comment]
@rpaasche I have checked for this, and this is not an issue.

The root cause for this is because there's a latency between:
1. user taps `cancel` in `iOS`'s default NFC prompt UI
2. `iOS` fires a delegation callback `didInvalidateWithError` to our objective-c codes to notify us the NFC session is closed. 

This latency between step 1 and 2 is about 600~800 ms (not precise, just a feeling), and that's not what we can control.

So, in order handle this `double-tapping` issue, we can consider to disable the button during the full session, for example:

```javascript
    setButtonEnabled(false); // <-- ADD THIS
    try {
      await NfcManager.requestTechnology([NfcTech.Ndef]);

      tag = await NfcManager.getTag();
      console.log(tag);
    } catch (ex) {
      // for tag reading, we don't actually need to show any error
      console.log(ex);
    } finally {
      NfcManager.cancelTechnologyRequest();
    }
    setButtonEnabled(true); // <-- ADD THIS
```

BTW, the NFC session `cleanup` logic our library is actually happened inside `didInvalidateWithError`:

```objective-c
// NfcManager.m
- (void)tagReaderSession:(NFCTagReaderSession *)session didInvalidateWithError:(NSError *)error
    API_AVAILABLE(ios(13.0)) {
    NSLog(@"NFCTag didInvalidateWithError");
    if (techRequestCallback) {
        techRequestCallback(@[getErrorMessage(error)]);
        techRequestCallback = nil;
    }

    [self reset]; // <-- CHECK HERE: this function will clean current session
    [self sendEventWithName:@"NfcManagerSessionClosed"
                       body:@{@"error": getErrorMessage(error)}];
}
```

That's why you might get `duplicated registration` while you trigger the NFC scanning during the above latency.

**Comment by whitedogg13** [comment]
close for now, please feel free to reopen if there's still anything unclear.
