### ISSUE TITLE
Course Demo First Example

### ISSUE THREAD

**Issue by edulecca** [revtel/react-native-nfc-manager#530]
I'm trying to implement/refactor the course's Game example given on the first chapter

```
React.useEffect(() => {
        let count = 5;
        NfcManager.setEventListener(NfcEvents.DiscoverTag, (tag) => {
            count--;
            NfcManager.setAlertMessageIOS(`${count}...`);
            if (count <= 0) {
                NfcManager.unregisterTagEvent().catch(() => 0);
                setDuration(new Date().getTime() - start.getTime());
            }
        });

        return () => {
            NfcManager.setEventListener(NfcEvents.DiscoverTag, null);
        };
    }, [start]);
```

but no able to refacotr with the  `await NfcManager.requestTechnology([NfcTech.Ndef])` method suggesed
couldnt figure it out how to put it work the `NfcManager.setEventListener(NfcEvents.DiscoverTag ...` event

**Comment by whitedogg13** [comment]
Hi @edulecca thanks for your support!

You're right, the `requestTechnology` won't emit `DiscoverTag` event, so that's why you won't be able to receive it.

Per my point, the `Game` logic is designed to demonstrate `registerTagEvent` approach, which is different from `requestTechnology` approach, so try to use `requestTechnology` for refactoring is not suggested.

Thanks!

**Comment by edulecca** [comment]
ty @whitedogg13 appreciate your course and your work done
